export const CHARACTERS = [
  {
    id: 'sam',
    name: 'Sam',
    color: '#f0c674',
    rounds: 3,
    strategyId: 'allC',
    intro: "Sam. The friend who covered your rent that month you don't talk about. You've never paid him back and he's never asked.",
    summaryC: [
      "Sam always shared.",
      "He would have kept going as long as you did.",
    ],
    summaryD: [
      "Sam always shared. Even when you didn't.",
      "He never asked you to stop.",
    ],
    revealName: 'Always Cooperate',
    revealExplanation: "Sam shared every round, no matter what. Always Cooperate. It's the most generous strategy. It's also the easiest to exploit. The world is harder on Sams than it should be.",
  },
  {
    id: 'marcus',
    name: 'Marcus',
    color: '#a23b3b',
    rounds: 3,
    strategyId: 'allD',
    intro: "Marcus. Your old roommate. He still owes you for the last two months of utilities. He's been saying he'll pay you back since 2019.",
    summaryC: [
      "He always took. That was the play.",
      "Nothing you did was going to change the math. You kept sharing. He kept taking. That's who Marcus is.",
    ],
    summaryD: [
      "He always took. That was the play.",
      "Nothing you did was going to change the math.",
    ],
    revealName: 'Always Defect',
    revealExplanation: "Marcus took every round, no matter what. Always Defect. It can't be reasoned with, but it also can't build anything. Against another AllD, the result is mutual destruction. The strategies that do best long-term all start by cooperating.",
  },
  {
    id: 'maya',
    name: 'Maya',
    color: '#5e8ca8',
    rounds: 8,
    strategyId: 'tft',
    intro: "Maya. Your business partner. Three years and she's never once taken more than her share.",
    summaryC: [
      "She was just matching you.",
      "Maya would have given you everything if you had. Whatever you chose, she chose back. The first move was always yours.",
    ],
    summaryD: [
      "She was just matching you.",
      "You took, so she took. You gave her nothing to work with. She would have cooperated every round if you had started differently. The first move was always yours.",
    ],
    revealName: 'Tit-for-Tat',
    revealExplanation: "Maya did whatever you did last round. Tit-for-Tat. Cooperate first, then mirror. It won the first computer tournament of this kind, run by Robert Axelrod in 1980. Simple, fair, and hard to exploit.",
  },
  {
    id: 'theo',
    name: 'Theo',
    color: '#c87635',
    rounds: 5,
    strategyId: 'grim',
    intro: "Your cousin Theo. He hasn't spoken to your aunt since 2017. Nobody else in the family remembers what she did.",
    summaryC: [
      "Theo gave generously. You gave generously back.",
      "He would have kept going. Some people just need to know you're not going to hurt them.",
    ],
    summaryD: [
      "Theo gave generously, right up until you took.",
      "After that, nothing you did mattered. There was no apology that would have worked. He had already closed the door.",
    ],
    revealName: 'Grim Trigger',
    revealExplanation: "Theo cooperated until you betrayed him, then defected forever. Grim Trigger. It cooperates, until it doesn't. After that, the door is closed.",
  },
  {
    id: 'naomi',
    name: 'Naomi',
    color: '#a085bd',
    rounds: 5,
    strategyId: 'tf2t',
    intro: "Your sister Naomi. She's the patient one. She always has been.",
    summaryC: [
      "Naomi let things go. Because you let things go.",
      "She wasn't naive — she was watching the whole time. She just gave you room to be a person. You did.",
    ],
    summaryD: [
      "Naomi let things slide. Once. Twice, sometimes.",
      "She wasn't naive — she was watching the whole time. She just gave you room to be a person. Until you weren't.",
    ],
    revealName: 'Tit-for-Two-Tats',
    revealExplanation: "Naomi needed two defections in a row before she'd retaliate. Tit-for-Two-Tats. More forgiving than the mirror. In the real world, where people make mistakes, that forgiveness often makes it more stable.",
  },
  {
    id: 'ren',
    name: 'Ren',
    color: '#4c9c6a',
    rounds: 8,
    strategyId: 'pavlov',
    intro: "Ren. The friend who thinks in patterns. You've never quite been able to predict them.",
    summaryC: [
      "Ren wasn't watching you. They were watching what happened.",
      "Whatever worked, they kept. Whatever didn't, they dropped. And sharing kept working — so they kept sharing.",
    ],
    summaryD: [
      "Ren wasn't watching you. They were watching what happened.",
      "Whatever worked, they kept. Whatever didn't, they dropped. You made taking work, so they took.",
    ],
    revealName: 'Win-Stay, Lose-Shift',
    revealExplanation: "Ren used Win-Stay, Lose-Shift. If a round went well, repeat it. If it went badly, switch. Not watching you — watching outcomes. It's adaptive, not reactive, and it's surprisingly robust against both cooperators and defectors.",
  },
];
